<a href="https://colab.research.google.com/github/ThanikPimpiban/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Structure(โครงสร้างข้อมูล)**

การเก็บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นระเบียบ

list()

* เก็บอะไรก็ได้
* ลำดับในการเก็บ มีความสำคัญ

In [10]:
list_a = [1,2,3,4,5,6]  #[ ] square brackets

In [11]:
list_a #ดู list 

[1, 2, 3, 4, 5, 6]

In [12]:
list_b = ['ab',2,3.14,list_a] #สร้าง list

In [13]:
list_b #ดู list 

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

**indexing การชี้สมาชิกใน list ด้วย เลขลำดับของ list**

In [14]:
list_a[3] # list ตัวที่ 4

4

In [15]:
list_b[3]  # list ตัวที่ 4

[1, 2, 3, 4, 5, 6]

In [16]:
list_b[3][4]

5

In [17]:
#list_a[6]

In [18]:
list_a[-1] #index -1 คือตัวสุดท้ายของ list

6

In [19]:
list_a[-4]

3

**การสร้าง list()**

In [20]:
list_x1 = [] #แบบที่ 1
list_x2 = list() #แบบที่ 2

In [21]:
print(list_x1)
print(list_x2)

[]
[]


**เพิ่มสมาชิกเข้าไปใน list ด้วย append()**

In [22]:
list_x1.append(2) #เพิ่ม list

In [23]:
list_x1

[2]

In [24]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [25]:
list_x1[0]

2

In [26]:
list_x1[-1]

4

In [27]:
list_x2

[]

In [28]:
list_x2.append('ha')

In [29]:
list_x2

['ha']

**ลบสมาชิกจาก list**

In [30]:
list_x1.append('ha')

In [31]:
list_x1

[2, 4, 'ha']

In [32]:
list_x1.pop()

'ha'

In [33]:
list_x1

[2, 4]

In [34]:
list_x1.pop()
print(list_x1)

[2]


**len() ตรวจสอบจำนวนสมาชิกของ list**

In [35]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [36]:
len(list_a) #ตรวจจำนวน list

6

**String is a list of characters**

In [37]:
st_stat = 'Department of Statistics, Faculty of Science'

In [38]:
st_stat[10]

' '

In [39]:
len(st_stat) #ตรวจจำนวนตัวอักษร

44

**List Slicing :**

list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]

list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง):step]

In [40]:
list_a

[1, 2, 3, 4, 5, 6]

In [41]:
list_a[2]

3

**: colon**

In [42]:
list_a[-3:]

[4, 5, 6]

In [43]:
list_a[:4]

[1, 2, 3, 4]

In [44]:
list_a[1:4]

[2, 3, 4]

In [45]:
list_a[:]

[1, 2, 3, 4, 5, 6]

**step**

In [46]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [47]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [48]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [49]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

**range()**

In [50]:
range(21)

range(0, 21)

In [51]:
a = list(range(21))

In [52]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [53]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)

* 12:30:15
* 13:41:07
* 09:11:50
* 21:30:15
* 03:10:15

In [54]:
T = ['12:30:15','13:41:07','09:11:50','21:30:15','03:10:15']

In [55]:
for i in range(5) :
    HW = T[i].split(':')
    a = (int(HW[0])*60*60) + (int(HW[1])*60) + int(HW[2])
    print(f'{T[i]} คำนวณเป็นวินาทีได้ {a} วินาที')

12:30:15 คำนวณเป็นวินาทีได้ 45015 วินาที
13:41:07 คำนวณเป็นวินาทีได้ 49267 วินาที
09:11:50 คำนวณเป็นวินาทีได้ 33110 วินาที
21:30:15 คำนวณเป็นวินาทีได้ 77415 วินาที
03:10:15 คำนวณเป็นวินาทีได้ 11415 วินาที


**Dictionary**

* คล้าย list()
* index เป็นอะไรก็ได้ไม่จำเป็นต้องเป็นตัวเลขลำดับ

In [56]:
dict_a = {1:'Happy','N':'New','2022':'Year'}  # Curly brackets

In [62]:
dict_a['N']

'New'

In [63]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [64]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

## การเพิ่มสมาชิกลงไปใน dictionary

In [65]:
dict_a[7]= 3.14

In [66]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [68]:
dict_a['N'] = 'NNNNEEEEWWWW' ##ใช้ key ซ้ำ จะถูก update ใหม่

In [69]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

**Numpy Array**

* เก็บได้แค่ตัวเลข
* อ้างอิงโดยใช้ พิกัด (2มิติ มองเป็น Martrix)

In [70]:
import numpy as np

In [71]:
arr_a = np.array([1,2,3,4,5])

In [72]:
arr_a 

array([1, 2, 3, 4, 5])

In [73]:
arr_a[1]

2

In [75]:
5* arr_a ## Matrix Scalar Multiple

array([ 5, 10, 15, 20, 25])

In [77]:
list_A = [1,2,3,4,5]

In [78]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [79]:
arr_b = np.array([10,20,30,40,50])

In [80]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

**2D Array**

## Pandas Dataframe (แยกออกเป็น notebook เฉพาะ)