<a href="https://colab.research.google.com/github/ThanikPimpiban/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Structure(โครงสร้างข้อมูล)**

การเก็บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นระเบียบ

list()

* เก็บอะไรก็ได้
* ลำดับในการเก็บ มีความสำคัญ

In [337]:
list_a = [1,2,3,4,5,6]  #[ ] square brackets

In [338]:
list_a #ดู list 

[1, 2, 3, 4, 5, 6]

In [339]:
list_b = ['ab',2,3.14,list_a] #สร้าง list

In [340]:
list_b #ดู list 

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]

**indexing การชี้สมาชิกใน list ด้วย เลขลำดับของ list**

In [341]:
list_a[3] # list ตัวที่ 4

4

In [342]:
list_b[3]  # list ตัวที่ 4

[1, 2, 3, 4, 5, 6]

In [343]:
list_b[3][4]

5

In [344]:
#list_a[6]

In [345]:
list_a[-1] #index -1 คือตัวสุดท้ายของ list

6

In [346]:
list_a[-4]

3

**การสร้าง list()**

In [347]:
list_x1 = [] #แบบที่ 1
list_x2 = list() #แบบที่ 2

In [348]:
print(list_x1)
print(list_x2)

[]
[]


**เพิ่มสมาชิกเข้าไปใน list ด้วย append()**

In [349]:
list_x1.append(2) #เพิ่ม list

In [350]:
list_x1

[2]

In [351]:
list_x1.append(4)
print(list_x1)

[2, 4]


In [352]:
list_x1[0]

2

In [353]:
list_x1[-1]

4

In [354]:
list_x2

[]

In [355]:
list_x2.append('ha')

In [356]:
list_x2

['ha']

**ลบสมาชิกจาก list**

In [357]:
list_x1.append('ha')

In [358]:
list_x1

[2, 4, 'ha']

In [359]:
list_x1.pop()

'ha'

In [360]:
list_x1

[2, 4]

In [361]:
list_x1.pop()
print(list_x1)

[2]


**len() ตรวจสอบจำนวนสมาชิกของ list**

In [362]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [363]:
len(list_a) #ตรวจจำนวน list

6

**String is a list of characters**

In [364]:
st_stat = 'Department of Statistics, Faculty of Science'

In [365]:
st_stat[10]

' '

In [366]:
len(st_stat) #ตรวจจำนวนตัวอักษร

44

**List Slicing :**

list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง)]

list[จุดเริ่มต้น (ทึบ):จุดสุดท้าย (โปร่ง):step]

In [367]:
list_a

[1, 2, 3, 4, 5, 6]

In [368]:
list_a[2]

3

**: colon**

In [369]:
list_a[-3:]

[4, 5, 6]

In [370]:
list_a[:4]

[1, 2, 3, 4]

In [371]:
list_a[1:4]

[2, 3, 4]

In [372]:
list_a[:]

[1, 2, 3, 4, 5, 6]

**step**

In [373]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13]

In [374]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [375]:
list_c[:10:2]

[1, 3, 5, 7, 9]

In [376]:
list_c[::-1]

[13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

**range()**

In [377]:
range(21)

range(0, 21)

In [378]:
a = list(range(21))

In [379]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [380]:
list(range(1,21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)

* 12:30:15
* 13:41:07
* 09:11:50
* 21:30:15
* 03:10:15

In [381]:
T = ['12:30:15','13:41:07','09:11:50','21:30:15','03:10:15']

In [382]:
for i in range(5) :
    HW = T[i].split(':')
    a = (int(HW[0])*60*60) + (int(HW[1])*60) + int(HW[2])
    print(f'{T[i]} คำนวณเป็นวินาทีได้ {a} วินาที')

12:30:15 คำนวณเป็นวินาทีได้ 45015 วินาที
13:41:07 คำนวณเป็นวินาทีได้ 49267 วินาที
09:11:50 คำนวณเป็นวินาทีได้ 33110 วินาที
21:30:15 คำนวณเป็นวินาทีได้ 77415 วินาที
03:10:15 คำนวณเป็นวินาทีได้ 11415 วินาที


**Dictionary**

* คล้าย list()
* index เป็นอะไรก็ได้ไม่จำเป็นต้องเป็นตัวเลขลำดับ

In [383]:
dict_a = {1:'Happy','N':'New','2022':'Year'}  # Curly brackets

In [384]:
dict_a['N']

'New'

In [385]:
dict_a.keys()

dict_keys([1, 'N', '2022'])

In [386]:
dict_a.values()

dict_values(['Happy', 'New', 'Year'])

## การเพิ่มสมาชิกลงไปใน dictionary

In [387]:
dict_a[7]= 3.14

In [388]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [389]:
dict_a['N'] = 'NNNNEEEEWWWW' ##ใช้ key ซ้ำ จะถูก update ใหม่

In [390]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEEEEWWWW'}

**Numpy Array**

* เก็บได้แค่ตัวเลข
* อ้างอิงโดยใช้ พิกัด (2มิติ มองเป็น Martrix)

In [391]:
import numpy as np

In [392]:
arr_a = np.array([1,2,3,4,5])

In [393]:
arr_a 

array([1, 2, 3, 4, 5])

In [394]:
arr_a[1]

2

In [395]:
5* arr_a ## Matrix Scalar Multiple

array([ 5, 10, 15, 20, 25])

In [396]:
list_A = [1,2,3,4,5]

In [397]:
5*list_A

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [398]:
arr_b = np.array([10,20,30,40,50])

In [399]:
arr_a + arr_b

array([11, 22, 33, 44, 55])

**2D Array**

In [400]:
import numpy as np

In [401]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [402]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [403]:
arr2_z.shape

(2, 3)

**np.zeros()**

In [404]:
arr2_3_5_0 = np.zeros((3,5))

In [405]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [406]:
arr2_3_5_0[1,2] = 9 

In [407]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [408]:
arr2_3_5_0[1,2]

9.0

In [409]:
print(list_A) # เปลี่ยนค่าใน list()
list_A[-1] = 'Christmas'
print(list_A)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 'Christmas']


**np.ones()**

In [410]:
arr2_4_5_1 = np.ones((4,5))

In [411]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [412]:
arr2_4_5_200 = 200*np.ones((4,5))

In [413]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

**Matrix operations**

* การบวก ลบ matrix  บวกลบตัวที่อยู่ตำแหน่งเดียวกัน


In [414]:
### การบวก ลบ matrix shape ต้องเท่ากัน

#arr2_4_5_200 + arr2_3_5_0

In [415]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

**การคูณ matrix**

*  scalar คูณ Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix)
* Matrix คูณ Matrix (แถวคูณหลัก)

In [416]:
5 * arr_a

array([ 5, 10, 15, 20, 25])

In [417]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [418]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [419]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [420]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

In [421]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [422]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

In [423]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [424]:
mat_X = np.dot(mat_c,mat_b)
print(mat_X)

[[  8  16 -11]
 [ 16  32 -22]
 [ 25  50 -28]]


In [425]:
mat_a * mat_b

array([[  2,   6,  25],
       [  8,  24, -49]])

**Matrix Slicing**

In [426]:
mat_X[:2,:2]

array([[ 8, 16],
       [16, 32]])

**HW 3**

* สร้าง array ที่เป็นรูป ต้น Christmas

* slice เลข 1 ออกมาจาก array HW3 ด้วยการ slice แค่ครั้งเดียว

In [427]:
### สร้างต้น Christmas

T = np.zeros((10,10))
T[::1,5] = 777
T[1:2,4:7] = 777
T[2:3,2:8] = 777
T[3:4,1:9] = 777
T[4:5,2:8] = 777
T[5:6,1:9] =777
T[6:7,0:10] = 777
T[7:8,4:7] =99
T[8:9,4:7] = 99
T[9:10,4:7] = 99
print(T)

[[  0.   0.   0.   0.   0. 777.   0.   0.   0.   0.]
 [  0.   0.   0.   0. 777. 777. 777.   0.   0.   0.]
 [  0.   0. 777. 777. 777. 777. 777. 777.   0.   0.]
 [  0. 777. 777. 777. 777. 777. 777. 777. 777.   0.]
 [  0.   0. 777. 777. 777. 777. 777. 777.   0.   0.]
 [  0. 777. 777. 777. 777. 777. 777. 777. 777.   0.]
 [777. 777. 777. 777. 777. 777. 777. 777. 777. 777.]
 [  0.   0.   0.   0.  99.  99.  99.   0.   0.   0.]
 [  0.   0.   0.   0.  99.  99.  99.   0.   0.   0.]
 [  0.   0.   0.   0.  99.  99.  99.   0.   0.   0.]]


In [428]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [429]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [430]:
### slice เลข 1 
HW3[::4,2::2]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Pandas Dataframe (แยกออกเป็น notebook เฉพาะ)